import re
from dataclasses import dataclass

from crewai import Crew, Task, Process

from backend.agents.agents import (
    make_generator_agent,
    make_reviewer_agent,
    make_cleanup_agent,
)
from backend.services.requirements_guard import ensure_requirements_clarity


@dataclass
class GenerationResult:
    generated_terraform: str
    reviewed_terraform: str
    change_summary: str
    cleanup_script: str


def _extract_hcl(text: str) -> str:
    """Pull HCL out of ```hcl ... ``` fences."""
    match = re.search(r"```hcl\s*(.*?)```", text, re.DOTALL)
    return match.group(1).strip() if match else text.strip()


def _extract_bash(text: str) -> str:
    match = re.search(r"```bash\s*(.*?)```", text, re.DOTALL)
    return match.group(1).strip() if match else text.strip()


def _parse_review_output(text: str) -> tuple[str, str]:
    """Split reviewer output into (corrected_hcl, change_summary)."""
    s1_marker = "SECTION 1 - CORRECTED TERRAFORM:"
    s2_marker = "SECTION 2 - CHANGE SUMMARY:"
    if s1_marker in text and s2_marker in text:
        s1 = text.split(s1_marker, 1)[1].split(s2_marker, 1)[0]
        s2 = text.split(s2_marker, 1)[1].strip()
        return _extract_hcl(s1), s2
    # Fallback: treat whole output as terraform
    return _extract_hcl(text), "No change summary provided."


def run_crew(requirements: str, services: list[str]) -> GenerationResult:
    """Execute the full 3-agent sequential pipeline."""
    ensure_requirements_clarity(requirements, services)

    services_str = ", ".join(services) if services else "not specified"
    prompt_context = (
        f"Infrastructure requirements:\n{requirements}\n\n"
        f"OCI services to use: {services_str}"
    )

    generator = make_generator_agent()
    reviewer = make_reviewer_agent()
    cleanup_agent = make_cleanup_agent()

    generate_task = Task(
        description=(
            f"Generate a complete OCI Terraform script for the following:\n\n{prompt_context}\n\n"
            "Output ONLY valid HCL inside a single ```hcl code block."
        ),
        expected_output="Complete OCI Terraform HCL in a ```hcl code block.",
        agent=generator,
    )

    review_task = Task(
        description=(
            "Review the Terraform code generated by the previous task for CIS OCI Benchmark "
            "v2.0 compliance. Fix any violations. Output exactly:\n"
            "SECTION 1 - CORRECTED TERRAFORM: (full HCL)\n"
            "SECTION 2 - CHANGE SUMMARY: (bullet list of changes)"
        ),
        expected_output=(
            "SECTION 1 - CORRECTED TERRAFORM followed by SECTION 2 - CHANGE SUMMARY."
        ),
        agent=reviewer,
        context=[generate_task],
    )

    cleanup_task = Task(
        description=(
            "Using the reviewed Terraform code as reference, write a safe bash cleanup "
            "script that destroys all resources in correct dependency order, with a "
            "confirmation prompt and full logging."
        ),
        expected_output="A complete bash cleanup script in a ```bash code block.",
        agent=cleanup_agent,
        context=[review_task],
    )

    crew = Crew(
        agents=[generator, reviewer, cleanup_agent],
        tasks=[generate_task, review_task, cleanup_task],
        process=Process.sequential,
        verbose=True,
    )

    result = crew.kickoff()

    # Extract outputs from task results
    raw_gen = str(generate_task.output) if generate_task.output else ""
    raw_rev = str(review_task.output) if review_task.output else ""
    raw_cleanup = str(cleanup_task.output) if cleanup_task.output else ""

    reviewed_tf, change_summary = _parse_review_output(raw_rev)

    return GenerationResult(
        generated_terraform=_extract_hcl(raw_gen),
        reviewed_terraform=reviewed_tf,
        change_summary=change_summary,
        cleanup_script=_extract_bash(raw_cleanup),
    )


def run_refinement(
    current_reviewed_terraform: str,
    refinement_request: str,
    services: list[str],
) -> GenerationResult:
    """
    Refine existing reviewed Terraform based on a user change request.
    Uses reviewer + cleanup agents to avoid full regeneration on each chat turn.
    """
    if not current_reviewed_terraform.strip():
        raise ValueError("current_reviewed_terraform cannot be empty for refinement")
    if not refinement_request.strip():
        raise ValueError("refinement_request cannot be empty for refinement")

    services_str = ", ".join(services) if services else "not specified"
    reviewer = make_reviewer_agent()
    cleanup_agent = make_cleanup_agent()

    refine_task = Task(
        description=(
            "Refine the existing reviewed OCI Terraform according to the user's request, "
            "while preserving resources not explicitly changed. Keep CIS OCI Benchmark "
            "v2.0 compliance. Output exactly:\n"
            "SECTION 1 - CORRECTED TERRAFORM: (full updated HCL)\n"
            "SECTION 2 - CHANGE SUMMARY: (bullet list of updates)\n\n"
            f"Services in scope: {services_str}\n\n"
            "Current reviewed Terraform:\n"
            f"```hcl\n{current_reviewed_terraform}\n```\n\n"
            "User refinement request:\n"
            f"{refinement_request}"
        ),
        expected_output=(
            "SECTION 1 - CORRECTED TERRAFORM followed by SECTION 2 - CHANGE SUMMARY."
        ),
        agent=reviewer,
    )

    cleanup_task = Task(
        description=(
            "Based on the updated reviewed Terraform, produce a safe cleanup script "
            "with dependency-aware destruction order, confirmation prompt, and logging."
        ),
        expected_output="A complete bash cleanup script in a ```bash code block.",
        agent=cleanup_agent,
        context=[refine_task],
    )

    crew = Crew(
        agents=[reviewer, cleanup_agent],
        tasks=[refine_task, cleanup_task],
        process=Process.sequential,
        verbose=True,
    )
    crew.kickoff()

    raw_refined = str(refine_task.output) if refine_task.output else ""
    raw_cleanup = str(cleanup_task.output) if cleanup_task.output else ""
    reviewed_tf, change_summary = _parse_review_output(raw_refined)

    return GenerationResult(
        generated_terraform=_extract_hcl(current_reviewed_terraform),
        reviewed_terraform=reviewed_tf,
        change_summary=change_summary,
        cleanup_script=_extract_bash(raw_cleanup),
    )


def run_generate_only(requirements: str, services: list[str]) -> str:
    """
    Run only generator agent and return Terraform draft.
    """
    ensure_requirements_clarity(requirements, services)
    services_str = ", ".join(services) if services else "not specified"
    prompt_context = (
        f"Infrastructure requirements:\n{requirements}\n\n"
        f"OCI services to use: {services_str}"
    )

    generator = make_generator_agent()
    generate_task = Task(
        description=(
            f"Generate a complete OCI Terraform script for the following:\n\n{prompt_context}\n\n"
            "Output ONLY valid HCL inside a single ```hcl code block."
        ),
        expected_output="Complete OCI Terraform HCL in a ```hcl code block.",
        agent=generator,
    )
    crew = Crew(
        agents=[generator],
        tasks=[generate_task],
        process=Process.sequential,
        verbose=True,
    )
    crew.kickoff()
    raw_gen = str(generate_task.output) if generate_task.output else ""
    return _extract_hcl(raw_gen)


def run_refinement_draft(
    current_generated_terraform: str,
    refinement_request: str,
    services: list[str],
) -> str:
    """
    Refine current Terraform draft without running reviewer/cleanup agents.
    """
    if not current_generated_terraform.strip():
        raise ValueError("current_generated_terraform cannot be empty for refinement")
    if not refinement_request.strip():
        raise ValueError("refinement_request cannot be empty for refinement")

    services_str = ", ".join(services) if services else "not specified"
    generator = make_generator_agent()
    refine_task = Task(
        description=(
            "Update the existing OCI Terraform draft based on the user refinement request. "
            "Preserve existing resources unless explicitly changed. Output ONLY valid HCL "
            "inside a single ```hcl code block.\n\n"
            f"Services in scope: {services_str}\n\n"
            "Current Terraform draft:\n"
            f"```hcl\n{current_generated_terraform}\n```\n\n"
            "Refinement request:\n"
            f"{refinement_request}"
        ),
        expected_output="Updated OCI Terraform HCL in a ```hcl code block.",
        agent=generator,
    )
    crew = Crew(
        agents=[generator],
        tasks=[refine_task],
        process=Process.sequential,
        verbose=True,
    )
    crew.kickoff()
    raw_refined = str(refine_task.output) if refine_task.output else ""
    return _extract_hcl(raw_refined)


def run_review_only(terraform_code: str) -> tuple[str, str]:
    """
    Run reviewer agent only on current Terraform and return (reviewed_tf, summary).
    """
    if not terraform_code.strip():
        raise ValueError("terraform_code cannot be empty for review")

    reviewer = make_reviewer_agent()
    review_task = Task(
        description=(
            "Review the provided Terraform for CIS OCI Benchmark v2.0 compliance. "
            "Fix violations and output exactly:\n"
            "SECTION 1 - CORRECTED TERRAFORM: (full HCL)\n"
            "SECTION 2 - CHANGE SUMMARY: (bullet list)\n\n"
            "Terraform to review:\n"
            f"```hcl\n{terraform_code}\n```"
        ),
        expected_output=(
            "SECTION 1 - CORRECTED TERRAFORM followed by SECTION 2 - CHANGE SUMMARY."
        ),
        agent=reviewer,
    )
    crew = Crew(
        agents=[reviewer],
        tasks=[review_task],
        process=Process.sequential,
        verbose=True,
    )
    crew.kickoff()
    raw_review = str(review_task.output) if review_task.output else ""
    return _parse_review_output(raw_review)


def run_cleanup_only(terraform_code: str) -> str:
    """
    Run cleanup agent only and return cleanup script.
    """
    if not terraform_code.strip():
        raise ValueError("terraform_code cannot be empty for cleanup generation")

    cleanup_agent = make_cleanup_agent()
    cleanup_task = Task(
        description=(
            "Using the provided Terraform code as reference, write a safe bash cleanup "
            "script that destroys resources in dependency-aware order with confirmation "
            "prompt and logging.\n\n"
            "Terraform input:\n"
            f"```hcl\n{terraform_code}\n```"
        ),
        expected_output="A complete bash cleanup script in a ```bash code block.",
        agent=cleanup_agent,
    )
    crew = Crew(
        agents=[cleanup_agent],
        tasks=[cleanup_task],
        process=Process.sequential,
        verbose=True,
    )
    crew.kickoff()
    raw_cleanup = str(cleanup_task.output) if cleanup_task.output else ""
    return _extract_bash(raw_cleanup)
