import re
from dataclasses import dataclass

from crewai import Crew, Task, Process

from backend.agents.agents import (
    make_generator_agent,
    make_reviewer_agent,
    make_cleanup_agent,
)


@dataclass
class GenerationResult:
    generated_terraform: str
    reviewed_terraform: str
    change_summary: str
    cleanup_script: str


def _extract_hcl(text: str) -> str:
    """Pull HCL out of ```hcl ... ``` fences."""
    match = re.search(r"```hcl\s*(.*?)```", text, re.DOTALL)
    return match.group(1).strip() if match else text.strip()


def _extract_bash(text: str) -> str:
    match = re.search(r"```bash\s*(.*?)```", text, re.DOTALL)
    return match.group(1).strip() if match else text.strip()


def _parse_review_output(text: str) -> tuple[str, str]:
    """Split reviewer output into (corrected_hcl, change_summary)."""
    s1_marker = "SECTION 1 - CORRECTED TERRAFORM:"
    s2_marker = "SECTION 2 - CHANGE SUMMARY:"
    if s1_marker in text and s2_marker in text:
        s1 = text.split(s1_marker, 1)[1].split(s2_marker, 1)[0]
        s2 = text.split(s2_marker, 1)[1].strip()
        return _extract_hcl(s1), s2
    # Fallback: treat whole output as terraform
    return _extract_hcl(text), "No change summary provided."


def run_crew(requirements: str, services: list[str]) -> GenerationResult:
    """Execute the full 3-agent sequential pipeline."""
    services_str = ", ".join(services) if services else "not specified"
    prompt_context = (
        f"Infrastructure requirements:\n{requirements}\n\n"
        f"OCI services to use: {services_str}"
    )

    generator = make_generator_agent()
    reviewer = make_reviewer_agent()
    cleanup_agent = make_cleanup_agent()

    generate_task = Task(
        description=(
            f"Generate a complete OCI Terraform script for the following:\n\n{prompt_context}\n\n"
            "Output ONLY valid HCL inside a single ```hcl code block."
        ),
        expected_output="Complete OCI Terraform HCL in a ```hcl code block.",
        agent=generator,
    )

    review_task = Task(
        description=(
            "Review the Terraform code generated by the previous task for CIS OCI Benchmark "
            "v2.0 compliance. Fix any violations. Output exactly:\n"
            "SECTION 1 - CORRECTED TERRAFORM: (full HCL)\n"
            "SECTION 2 - CHANGE SUMMARY: (bullet list of changes)"
        ),
        expected_output=(
            "SECTION 1 - CORRECTED TERRAFORM followed by SECTION 2 - CHANGE SUMMARY."
        ),
        agent=reviewer,
        context=[generate_task],
    )

    cleanup_task = Task(
        description=(
            "Using the reviewed Terraform code as reference, write a safe bash cleanup "
            "script that destroys all resources in correct dependency order, with a "
            "confirmation prompt and full logging."
        ),
        expected_output="A complete bash cleanup script in a ```bash code block.",
        agent=cleanup_agent,
        context=[review_task],
    )

    crew = Crew(
        agents=[generator, reviewer, cleanup_agent],
        tasks=[generate_task, review_task, cleanup_task],
        process=Process.sequential,
        verbose=True,
    )

    result = crew.kickoff()

    # Extract outputs from task results
    raw_gen = str(generate_task.output) if generate_task.output else ""
    raw_rev = str(review_task.output) if review_task.output else ""
    raw_cleanup = str(cleanup_task.output) if cleanup_task.output else ""

    reviewed_tf, change_summary = _parse_review_output(raw_rev)

    return GenerationResult(
        generated_terraform=_extract_hcl(raw_gen),
        reviewed_terraform=reviewed_tf,
        change_summary=change_summary,
        cleanup_script=_extract_bash(raw_cleanup),
    )
